### ISSUE TITLE
Button "Chart more data" does not work

### ISSUE THREAD

**Issue by karolinnger** [backmeupplz/borodutch#27]
#1
Issue: Button "Chart more data" (at Projects table) does not work and dissapears
Steps to reproduce:
1. Open website https://borodutch.com/
2. Scroll down to "Projects"
3. Push the button "Chart more data"
Actual result: After you push the button, it disappears and nothing happened

#2
Issue: Button "Chart more data" not changing to button "Hide all stats"
Steps to reproduce:
1. Open website https://borodutch.com/
2. Scroll down to "Voicy" in "Projects" table
3. Push the button "Show stats"
Actual result: Button "Chart more data" not changing to button "Hide all stats". And then If you push button "Chart more data" it will changing to button "Hide all stats".

#3
Issue: Button "Chart more data" changing to button "Hide all stats" after you push it
Steps to reproduce:
1. Open website https://borodutch.com/
2. Scroll down to "Voicy" in "Projects" table
3. Push the button "Show stats"
4. Push the button "Hide stats"
5. Scroll up to "Projects"
6. Push the button "Chart more data"
Actual result: Button "Chart more data" changing to the button "Hide all stats". If you push the button "Hide all stats" it will disappear and shown again if you push one of the "Shown stats" buttons.

[https://youtu.be/baEI00T-KoY](url) Video with steps and bugs

**Comment by backmeupplz** [comment]
This is all intended.

**Comment by karolinnger** [comment]
Got it, performance comes first 👍
