### ISSUE TITLE
404 error for one of the references

### ISSUE THREAD

**Issue by karolinnger** [backmeupplz/borodutch#28]
#1
Issue: Link "[Spark: Личный опыт: как запустить проект в одиночку](https://spark.ru/startup/voicy/blog/19008/kak-zapustit-proekt-v-odinochku/)" leads to 404 error page
Steps:
1. Open website https://borodutch.com/
2. Scroll down to "Voicy" in "Projects" table
3. Push the button "Show stats"
4. Click on "Spark: Личный опыт: как запустить проект в одиночку" link
Actual result: Link lead to page with 404 error
<img width="1440" alt="Screen Shot 2022-05-04 at 3 09 45 PM" src="https://user-images.githubusercontent.com/104932164/166808470-340f493f-1e5f-48b6-9900-d0efb909df06.png">

#2
Issue: Link "[Market Watch](https://www.marketwatch.com/press-release/borodutch-labs-nikita-kolmogorov-sells-shieldy-with-20m-users-to-1inch-network-in-the-largest-telegram-bot-deal-so-far-2021-06-05)" leads to 404 error page
Steps:
1. Open website https://borodutch.com/
2. Scroll down to "Shieldy" in "Projects" table
3. Push the button "Show stats"
4. Click on "[Market Watch](https://www.marketwatch.com/press-release/borodutch-labs-nikita-kolmogorov-sells-shieldy-with-20m-users-to-1inch-network-in-the-largest-telegram-bot-deal-so-far-2021-06-05)" link
Actual result: Link lead to page with 404 error
<img width="1440" alt="Screen Shot 2022-05-04 at 3 15 03 PM" src="https://user-images.githubusercontent.com/104932164/166809271-93171765-3dc3-415f-be6f-8c0d9065813c.png">

**Comment by backmeupplz** [comment]
Fixed, thank you!
