### ISSUE TITLE
error for one of the references #2

### ISSUE THREAD

**Issue by karolinnger** [backmeupplz/borodutch#29]
#1
Issue: Link "[CoinNews Nation: This app makes it super easy to write smart contracts for Ethereum](https://coinnewsnation.com/2018/08/this-app-makes-it-super-easy-to-write-smart-contracts-for-ethereum/)" leads to error page 
Steps:
1. Open website https://borodutch.com/
2. Scroll down to "Fondu" in "Projects" table
3. Push the button "Show stats"
4. Click on "[CoinNews Nation: This app makes it super easy to write smart contracts for Ethereum](https://coinnewsnation.com/2018/08/this-app-makes-it-super-easy-to-write-smart-contracts-for-ethereum/)" link
Actual result: Link lead to page with DNS_PROBE_FINISHED_NXDOMAIN error
<img width="1440" alt="Screen Shot 2022-05-04 at 3 39 37 PM" src="https://user-images.githubusercontent.com/104932164/166813074-9cc98a01-5526-4a66-8334-370f6206199a.png">

#2
Issue: Link "[Chepicap: New Fondu app lets users create Ethereum smart contracts more easily](https://www.chepicap.com/en/news/2745/new-fondu-app-lets-users-create-ethereum-smart-contracts-more-easily.html)" leads to error page 
Steps:
1. Open website https://borodutch.com/
2. Scroll down to "Fondu" in "Projects" table
3. Push the button "Show stats"
4. Click on "[Chepicap: New Fondu app lets users create Ethereum smart contracts more easily](https://www.chepicap.com/en/news/2745/new-fondu-app-lets-users-create-ethereum-smart-contracts-more-easily.html)" link
Actual result: Link lead to wrong page (domain not exist)
<img width="1440" alt="Screen Shot 2022-05-04 at 3 43 19 PM" src="https://user-images.githubusercontent.com/104932164/166813781-9bd0856d-3e1e-4879-a5fc-3ed9d26c1375.png">

That's all what I find for today at https://borodutch.com/. Thanks!

**Comment by backmeupplz** [comment]
Fixed, thank you!
